-- begin CEOTOCF_ORDER
alter table CEOTOCF_ORDER add constraint FK_CEOTOCF_ORDER_ON_DELIVERY_ADDRESS foreign key (DELIVERY_ADDRESS_ID) references CEOTOCF_ADDRESS(ID)^
alter table CEOTOCF_ORDER add constraint FK_CEOTOCF_ORDER_ON_CUSTOMER foreign key (CUSTOMER_ID) references CEOTOCF_CUSTOMER(ID)^
create index IDX_CEOTOCF_ORDER_ON_DELIVERY_ADDRESS on CEOTOCF_ORDER (DELIVERY_ADDRESS_ID)^
create index IDX_CEOTOCF_ORDER_ON_CUSTOMER on CEOTOCF_ORDER (CUSTOMER_ID)^
-- end CEOTOCF_ORDER
-- begin CEOTOCF_CUSTOMER
alter table CEOTOCF_CUSTOMER add constraint FK_CEOTOCF_CUSTOMER_ON_INVOICE_ADDRESS foreign key (INVOICE_ADDRESS_ID) references CEOTOCF_ADDRESS(ID)^
create index IDX_CEOTOCF_CUSTOMER_ON_INVOICE_ADDRESS on CEOTOCF_CUSTOMER (INVOICE_ADDRESS_ID)^
-- end CEOTOCF_CUSTOMER
-- begin CEOTOCF_PRODUCER
alter table CEOTOCF_PRODUCER add constraint FK_CEOTOCF_PRODUCER_ON_ADDRESS foreign key (ADDRESS_ID) references CEOTOCF_ADDRESS(ID)^
create index IDX_CEOTOCF_PRODUCER_ON_ADDRESS on CEOTOCF_PRODUCER (ADDRESS_ID)^
-- end CEOTOCF_PRODUCER
