alter table CEOTOCF_PRODUCER add constraint FK_CEOTOCF_PRODUCER_ON_ADDRESS foreign key (ADDRESS_ID) references CEOTOCF_ADDRESS(ID);
create index IDX_CEOTOCF_PRODUCER_ON_ADDRESS on CEOTOCF_PRODUCER (ADDRESS_ID);
